[Test] update workflow script
Signed-off-by: Kent Huang <kent@infuseai.io>

diff --git a/.github/workflows/recce_ci.yml b/.github/workflows/recce_ci.yml
--- a/.github/workflows/recce_ci.yml
+++ b/.github/workflows/recce_ci.yml
@@ -61,14 +61,6 @@ jobs:
         run: |
           recce run --github-pull-request-url ${{ github.event.pull_request.html_url }}
 
-      - name: Procress Recce Run Error
-        if: failure()
-        run: |
-          if [ -f recce_error.log ]; then
-            echo "Recce CI failed. Please check the following error message:"
-            echo "::error::$(cat recce_error.log)"
-          fi
-
       - name: Archive Recce State File
         uses: actions/upload-artifact@v4
         id: recce-artifact-uploader
@@ -112,3 +104,10 @@ jobs:
         uses: thollander/actions-comment-pull-request@v2
         with:
           filePath: recce_summary.md
+
+      - name: Check Recce CI result
+        run: |
+          if [ -f recce_error.log ]; then
+            echo "::error title=Recce Run Failed:: `cat recce_error.log`"
+            exit 1
+          fi
